name: deploy

on:
  push:
    branches: main

env:
  REGION: us-central1

jobs:
    gke-deploy:
        name: deploy
        runs-on: ubuntu-latest
        permissions:
            contents: 'read'
            id-token: 'write'
    
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Google Auth
              id: auth
              uses: 'google-github-actions/auth@v2'
              with:
                token_format: access_token
                project_id: ${{ secrets.PROJECT_ID }}
                service_account: githubactions@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com
                workload_identity_provider: projects/52069167239/locations/global/workloadIdentityPools/website-dev-pool/providers/github-actions-provider
        
            - name: Docker Auth
              id: docker-auth
              uses: 'docker/login-action@v3'
              with:
                username: oauth2accesstoken
                password: ${{ steps.auth.outputs.access_token }}
                registry: ${{ env.REGION }}-docker.pkg.dev
        
            - name: Build the Docker image
              run: |
                docker build . -t ${{ env.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/tsnext/tsapp:latest
                docker push ${{ env.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/tsnext/tsapp:latest
